#!/bin/bash

offsec_conn() {
    echo "Loading $1 as OPENVPN config file"
    sudo openvpn --config ~/ovpn/$1
}
if [ -z "$1" ]; then
    prompt="Please select a file:"
    options=( $(find ~/ovpn -maxdepth 1 -print0 | cut -d "/" -f 8 | xargs -0) )

    PS3="$prompt "
    select opt in "${options[@]}" "Quit" ; do 
        if (( REPLY == 1 + ${#options[@]} )) ; then
            exit

        elif (( REPLY > 0 && REPLY <= ${#options[@]} )) ; then
            offsec_conn $opt
            break

        else
            echo "Invalid option. Try another one."
        fi
    done    
else
    offsec_conn $1
fi
 
