#!/bin/bash

echo ----------IP Assignments----------
ip -o a | awk '{print $2, $4}' | grep -v lo | column -t -N dev,IP -o "          " 

echo -e '\033[0m'
echo ----------Neighbors----------
printf %"$COLUMNS"s |tr " " "-"
ip -r -c -br n  | awk '{print $3, $2, $1  }' | column -t -N MAC,dev,host -o "          "

echo -e '\033[0m'
echo ----------Routes----------
printf %"$COLUMNS"s |tr " " "-"
ip -c  r 

echo -e '\033[0m'
echo ----------Net Connections----------
printf %"$COLUMNS"s |tr " " "-"
ss -utprnH | sort -k7 | awk '{gsub(".mustbe.family", ""); split(substr($7, 9), p, ","); split($5, src, ":"); print $1,  src[2], $6, p[1], p[2]} '  | column -t -s $' \t ' -N proto,srcPort,remote,proc
