#!/bin/bash
case $2 in

  'all')
    mibs=(
      'installed 1.3.6.1.2.1.25.6.3.1.2'
      'running 1.3.6.1.2.1.25.4.2.1.2'
      'user 1.3.6.1.4.1.77.1.2.25'
      'tcp 1.3.6.1.2.1.6.13.1.3'
      'path 1.3.6.1.2.1.25.4.2.1.4'
      'storage 1.3.6.1.2.1.25.2.3.1.4'
      'interface 1.3.6.1.2.1.2.2.1.2'
    )
    ;;

  'interface')
    mibs='interface 1.3.6.1.2.1.2.2.1.2'
    ;;

  'installed')
    mibs='installed 1.3.6.1.2.1.25.6.3.1.2'
    ;;

  'running')
    mibs='running 1.3.6.1.2.1.25.4.2.1.2'
    ;;

  'user')
    mibs='user 1.3.6.1.4.1.77.1.2.25'
    ;;

  'tcp')
    mibs='tcp 1.3.6.1.2.1.6.13.1.3'
    ;;

  'path')
    mibs='path1.3.6.1.2.1.25.4.2.1.4'
    ;;

  'storage')
    mibs='storage 1.3.6.1.2.1.25.2.3.1.4'
    ;;

  *)
    echo $2 is an uknown option
    echo 
    echo Current options are:
    echo    '[1] installed (programs)'
    echo    '[2] running (programs)'
    echo    '[3] user (accounts)'
    echo    '[4] tcp (local ports)'
    echo    '[5] (processes) path'
    echo    '[6] storage (units)'
    exit
esac

ip=$1
for mib in "${mibs[@]}"; do
  title=$(echo $mib | cut -d ' ' -f1)
  cmib=$(echo $mib | cut -d ' ' -f2)
  echo ====================
  echo =  [+] $ip
  echo =  {---] $title
  echo ====================
  snmpwalk -c public -v1 $1 $cmib -Oa
  echo
done
